[data]
file_path = data/sotu/0.csv
file_path2 = None
dataset = sotu
[proc]
agg_column= document
var_name= element
value_name= frequency_in_document
processing_type = freq
[output]
output_path = results/sotu/lvs.csv
output_dic = results/sotu/dic.csv 
sig_file = results/sotu/signatures.csv
graph = True
top = 25
sig_length = 200
short_names = False